# Generated by Django 4.0.6 on 2022-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.TextField(db_column='Num', primary_key=True, serialize=False)),
                ('order_number', models.TextField(blank=True, db_column='Order number', null=True)),
                ('price_usd', models.TextField(blank=True, db_column='Price_usd', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('price_rub', models.FloatField(blank=True, db_column='Price_rub', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
